# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"h\n\x10InferenceRequest\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\x12\x10\n\x08tile_map\x18\x02 \x01(\x0c\x12\x12\n\nsprite_map\x18\x03 \x01(\x0c\x12\x0f\n\x07is_dead\x18\x04 \x01(\x08\x12\x0e\n\x06reward\x18\x05 \x01(\x02\"#\n\x11InferenceResponse\x12\x0e\n\x06\x61\x63tion\x18\x01 \x03(\x05\x32Q\n\tInference\x12\x44\n\x07Predict\x12\x1b.inference.InferenceRequest\x1a\x1c.inference.InferenceResponseb\x06proto3')



_INFERENCEREQUEST = DESCRIPTOR.message_types_by_name['InferenceRequest']
_INFERENCERESPONSE = DESCRIPTOR.message_types_by_name['InferenceResponse']
InferenceRequest = _reflection.GeneratedProtocolMessageType('InferenceRequest', (_message.Message,), {
  'DESCRIPTOR' : _INFERENCEREQUEST,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:inference.InferenceRequest)
  })
_sym_db.RegisterMessage(InferenceRequest)

InferenceResponse = _reflection.GeneratedProtocolMessageType('InferenceResponse', (_message.Message,), {
  'DESCRIPTOR' : _INFERENCERESPONSE,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:inference.InferenceResponse)
  })
_sym_db.RegisterMessage(InferenceResponse)

_INFERENCE = DESCRIPTOR.services_by_name['Inference']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INFERENCEREQUEST._serialized_start=30
  _INFERENCEREQUEST._serialized_end=134
  _INFERENCERESPONSE._serialized_start=136
  _INFERENCERESPONSE._serialized_end=171
  _INFERENCE._serialized_start=173
  _INFERENCE._serialized_end=254
# @@protoc_insertion_point(module_scope)
